version: '3'
services:
  mysql_master:
    image: mysql:5.7
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 3002:3306
    volumes:
      - ./master/conf/mysql.cnf:/etc/my.cnf
      - ./master/data:/var/lib/mysql


